### ISSUE TITLE
サイトの更新検知

### ISSUE THREAD

**Issue by shosatojp** [uec-world-dominators/watchcat#1]

**Comment by shosatojp** [comment]
- diff表示

**Comment by shosatojp** [comment]
- SQLiteくらい？

**Comment by shosatojp** [comment]
- 再帰的

**Comment by tomy-0000** [comment]
サイト
- [Ⅰ類(情報系) 電気通信大学情報理工学域](https://www.c1.uec.ac.jp/)
- [学務情報システム](https://campusweb.office.uec.ac.jp/campusweb/)

**Comment by shosatojp** [comment]
認証

- Basic
- Shibboleth

**Comment by shosatojp** [comment]
- 内部ページ
